import { SupabaseClient } from '@supabase/supabase-js';
import { uploadFileToStorage } from './supabase-storage';
import { STORAGE_BUCKETS, STORAGE_FOLDERS } from './storage-config';

/**
 * Schema for `designer_requests` table (defined in Supabase migration):
 *   id UUID PRIMARY KEY DEFAULT gen_random_uuid()
 *   fabric_object_id TEXT NOT NULL UNIQUE     -- == fabric.data.designerJobId
 *   design_id TEXT                            -- productId or design identifier
 *   source_url TEXT NOT NULL                  -- original PNG uploaded by user
 *   requester_user_id UUID                    -- auth.uid() if logged in
 *   requester_name TEXT NOT NULL
 *   requester_contact TEXT NOT NULL
 *   request_note TEXT
 *   status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','completed','cancelled'))
 *   completed_url TEXT
 *   created_at TIMESTAMPTZ NOT NULL DEFAULT now()
 *   updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
 */

type DesignerRequestInputBase = {
  /** A new uuid generated by caller and also stored on fabric object. */
  jobId: string;
  /** productId or other design identifier so the designer can locate the canvas. */
  designId?: string | null;
  requesterName: string;
  requesterContact: string;
  requestNote?: string;
};

/**
 * Provide either a raw File (will be uploaded) OR an already-uploaded
 * sourceUrl (e.g. AI/PSD original that was uploaded earlier in the flow —
 * avoids a duplicate upload).
 */
export type DesignerRequestSubmitInput = DesignerRequestInputBase &
  ({ sourceFile: File } | { sourceUrl: string });

export type DesignerRequestSubmitResult =
  | { success: true; sourceUrl: string }
  | { success: false; error: string };

export async function submitDesignerRequest(
  supabase: SupabaseClient,
  input: DesignerRequestSubmitInput,
): Promise<DesignerRequestSubmitResult> {
  let sourceUrl: string;
  if ('sourceUrl' in input) {
    sourceUrl = input.sourceUrl;
  } else {
    const upload = await uploadFileToStorage(
      supabase,
      input.sourceFile,
      STORAGE_BUCKETS.USER_DESIGNS,
      STORAGE_FOLDERS.IMAGES,
    );
    if (!upload.success || !upload.url) {
      return { success: false, error: upload.error ?? '원본 파일 업로드 실패' };
    }
    sourceUrl = upload.url;
  }

  const { data: userData } = await supabase.auth.getUser();
  const userId = userData.user?.id ?? null;

  const { error } = await supabase.from('designer_requests').insert({
    fabric_object_id: input.jobId,
    design_id: input.designId ?? null,
    source_url: sourceUrl,
    requester_user_id: userId,
    requester_name: input.requesterName,
    requester_contact: input.requesterContact,
    request_note: input.requestNote ?? null,
    status: 'pending',
  });

  if (error) {
    return { success: false, error: error.message };
  }
  return { success: true, sourceUrl };
}

export async function markDesignerRequestCompleted(
  supabase: SupabaseClient,
  jobId: string,
  completedUrl: string,
): Promise<{ success: boolean; error?: string }> {
  const { error } = await supabase
    .from('designer_requests')
    .update({
      status: 'completed',
      completed_url: completedUrl,
      updated_at: new Date().toISOString(),
    })
    .eq('fabric_object_id', jobId);
  if (error) return { success: false, error: error.message };
  return { success: true };
}
